pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            KICKSTARTER
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://LeeMaman.github.io/
#
# 2. URL of this page
url:              http://LeeMaman.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           KickStarter
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://www.veinsworld.com
  #
  # URL of a cover photo of your project
  cover_image:    http://bit.ly/VEINPIC
  #
  
# 4. Your Twitter handle
twitter_handle:   Vein Kickstarter Dream
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
Hey everybody! im getting down
  


